### ISSUE TITLE
Check Code and add some documentation

### ISSUE THREAD

**Issue by zerasul** [durangoretro/Perdita#3]
Check the code and try to refactor.

* Try to generate constants and store in a sepparated .h files

* Check functions and try to separate in other .c and .h files

**Comment by Ruberald** [comment]
Could you please assign this to me? I want to try my hand at this.

**Comment by zerasul** [comment]
assigned

**Comment by Ruberald** [comment]
I made a PR, could you please review that?

**Comment by zerasul** [comment]
Impressive!

Thanks for the PR; im going to review it

**Comment by Ruberald** [comment]
> Impressive!
> 
> Thanks for the PR; im going to review it

Thank you so much, it's my first time aside from some practice PRs. Any tip is extremely appreciated.
